### ISSUE TITLE
Xyris Roadmap

### ISSUE THREAD

**Issue by Kfeavel** [panix-os-dev-team/Panix#146]
The ultimate goal for Xyris is to get a GUI application to run in user space. Here's the roadmap as we see it now (from a top-down perspective).

- [ ] Graphical Widget Library
- [ ] VFS (Virtual File System)
- [ ] Drivers
    - [ ] HDD (SCSI / ATA / SATA, etc.)
    - [x] VBE (VESA BIOS Extensions or VGA)
    - [ ] PCI(e)
- [ ] Direct Memory Access
- [ ] Hardware Abstraction Layer
- [ ] Driver Abstraction Layer
    - [ ] Ring 1 & 2 Execution
- [ ] ACPI (Advanced Configuration & Power Interface)
- [ ] IPC (Interprocess Communication)
    - [ ] Message Passing
    - [ ] Pipes
- [x] Add mutexes / semaphores to critical areas of kernel #160
    - [x] Multitasking Aware Mutexes & Semaphores #147

**Comment by Kfeavel** [comment]
![FigureLayersoftheI_Osoftwaresystem](https://user-images.githubusercontent.com/3119047/97766483-dbf80280-1aec-11eb-9113-60b883fe1631.jpg)

**Comment by AmilieDev** [comment]
Working on Pipes on my end. Shouldn't be too hard and can be checked off.
